#!/usr/bin/env sh
#YABAI STUFF

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# float system preferences. Most of these just diable Yabai form resizing them.
# sticky=off allows user to move around window freely without moving existing windows
yabai -m rule --add app="^System Preferences$" sticky=off layer=above manage=off
yabai -m rule --add app="^Microsoft To Do$" sticky=off layer=above manage=off
yabai -m rule --add app="^Transmission$" sticky=off layer=above manage=off
yabai -m rule --add app="^App Store$" sticky=off layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^TinkerTool" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^CustomShortcuts" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Tot$" manage=off
# turning off iTerm2's sticky fixed alt tab focus issue
# Actually it didn't 12/14/21
yabai -m rule --add app="^iTerm$" sticky=off manage=off
yabai -m rule --add app="^Preview$" sticky=off manage=off
yabai -m rule --add app="^Multitouch$" sticky=off manage=off
yabai -m rule --add app="^Bartender 4$" sticky=off manage=off
yabai -m rule --add app="^Reminders$" sticky=off manage=off
yabai -m rule --add app="^TextEdit$" sticky=off manage=off
yabai -m rule --add app="^balenaEtcher$" sticky=off manage=off
yabai -m rule --add app="^Amphetamine$" sticky=off manage=off
yabai -m rule --add app="^FaceTime$" sticky=off manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^QuickTime$" sticky=off manage=off
yabai -m rule --add app="^Elmedia$" sticky=off layer=above manage=off
yabai -m rule --add app="^Numi$" sticky=on layer=above manage=off
yabai -m rule --add app="^Terminal$" sticky=on layer=above manage=off
yabai -m rule --add app="^VirtualBox$" sticky=on layer=above manage=off
yabai -m rule --add app="^console$" manage=off

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Roboto:Regular:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
# yabai -m config status_bar_background_color  0xff4c566a
# yabai -m config status_bar_foreground_color  0xfF4c566a
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9 10 11 12
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
# New window spawns to the left if vertical split, or top if horizontal split
# yabai -m config window_placement first_child
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.16
yabai -m config window_shadow                on
yabai -m config window_border                off
# yabai -m config window_border_placement      inset # exterior
yabai -m config window_border_width          8
yabai -m config window_border_radius         8
yabai -m config active_window_border_topmost on
# yabai -m config active_window_border_color   0xff4c566a
# yabai -m config normal_window_border_color   0xff4c566a
yabai -m config active_window_opacity        1.00
yabai -m config normal_window_opacity        0.20
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
# bsp or float (default is bsp) 
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   4

# yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# yabai -m signal --add event=display_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-2-jsx\"'"

echo "yabai configuration loaded.."

#END
